### PR TITLE
Create odoo-install-script.sh for Raspberry PI 3

### PR DESCRIPTION
**Pull request by chris86tian**
create modified script for Raspberry Pi 3

### CODE REVIEW

**Comment by mbrehmer** [comment]
Why should somebody run an ERP on a credit card-sized single-board computer?

**Comment by chris86tian** [comment]
Why not? The Raspberry Pi 3 is a power full server, and also good for testings.

**Comment by mbrehmer** [comment]
It is, but nobody would use it as a prodictive server for a company.

**Comment by jarnosv** [comment]
why not? i think would be so useful for training and for start up. and who knows, maybe in the future can be as much as it takes from a server

**Comment by chris86tian** [comment]
Ok, if it is not requested / wanted. 
I close the comment and work on my own fork.
Also Thanks!

**Pull request closed without merging**
